### ISSUE TITLE
(Only for Requested Change) Please do not raise new PR just comment here with the PR number

### ISSUE THREAD

**Issue by Aman22sharma** [Aman22sharma/Hacktoberfest2021_beginner#173]

**Comment by GoGi2712** [comment]
> _No description provided._

PR number #200

**Comment by Kavs-123** [comment]
Hey @Aman22sharma, 
I worked on issue #52 and raised PR #237

**Comment by Kavs-123** [comment]
> _No description provided._

PR Number #237

**Comment by ghost** [comment]
Can I add a game using pygame module?

**Comment by Kavs-123** [comment]
> > _No description provided._
> 
> PR Number #237

Pls merge this @Aman22sharma
