### ISSUE TITLE
Printing Pattern in Python

### ISSUE THREAD

**Issue by kaverichavan** [Aman22sharma/Hacktoberfest2021_beginner#181]
Program to print pattern using "*"
I would like to add this program. Please assign this issue to me.

**Comment by SiddheshKanawade** [comment]
Please assign this to me.

**Comment by SiddheshKanawade** [comment]
also, which pattern do we need to print, sorry for this doubt but i am new to open source

**Comment by MashTerro** [comment]
I want to add python programs which prints patterns, can you please assign this issue to me

**Comment by kaverichavan** [comment]
Please open this PR, I forget to push the code
