### ISSUE TITLE
Add Python Concept

### ISSUE THREAD

**Issue by Aman22sharma** [Aman22sharma/Hacktoberfest2021_beginner#52]

**Comment by drishyadamodaran** [comment]
Can I contribute?

**Comment by Aman22sharma** [comment]
@drishyadamodaran Yaa you can

**Comment by drishyadamodaran** [comment]
> @drishyadamodaran Yaa you can

pls check it

**Comment by kingofnoobs0** [comment]
can i add c++ code

**Comment by CHHAYANKSINGH** [comment]
@Aman22sharma can I contribute? I have good knowledge of python.

**Comment by Aman22sharma** [comment]
@CHHAYANKSINGH yaa sure you can 
@kingofnoobs0 no only python

**Comment by avyayjain** [comment]
can i contribute a concept of modules of python

**Comment by mayankgoyal-13** [comment]
added a pull request #70

**Comment by BoyWhoLived12** [comment]
Can I contribute as well?

**Comment by Aman22sharma** [comment]
@avyayjain yaa sure
@BoyWhoLived12 yes

**Comment by Aman22sharma** [comment]
> added a pull request #70

Done

**Comment by Udyansingh** [comment]
@avyayjain Please assign this issue to me.

**Comment by ayushjain27** [comment]
Please assign me I want to contribute

**Comment by Kavs-123** [comment]
Hey @Aman22sharma ,
Can u pls assign this to me?
Would be happy to contribute!
Thank You!

**Comment by Kapil-Tamang** [comment]
can I contribute for python

**Comment by avyayjain** [comment]
pls review my pr
avyay jain

**Comment by vivekarora-02** [comment]
Hey there,
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!

**Comment by kushgupta03** [comment]
Respected sir, I would like to contribute towards the repair of this issue, can you please assign me this issue?
It would be very kind of you to do so.
Thank You!

**Comment by RESHU-05** [comment]
Please assign  this issue to me . I want to contribute.

**Comment by mayankgoyal-13** [comment]
i have added a pull request #150

**Comment by AshishG97** [comment]
please assign this issue to me.

**Comment by Aman22sharma** [comment]
Guy's you can directly contribute your contribution by making a pull request. Whatever you want to contribute you can just raise a pull request we will review it and then merge it for hacktoberfest valid contribution. Thank you

**Comment by Aman22sharma** [comment]
@edusanketdk Hey this project is participating in hacktoberfest thank you

**Comment by Kavs-123** [comment]
Hey @Aman22sharma , 
I have raised a PR #237 ..pls review it and merge the same if sounds good :)
Thanks!

**Comment by ishika1661** [comment]
Hello! Can I contribute to this issue? Thank you.

**Comment by mayankgoyal-13** [comment]
> @edusanketdk Hey this project is participating in hacktoberfest thank you

But in my profile, it is showing excluded project 
![image](https://user-images.githubusercontent.com/65842833/137110103-0acf1db2-5f8a-4cc6-b802-9fde22857c77.png)

**Comment by Prashant0kgp** [comment]
@Aman22sharma  adding KMP concept #243 once check  and review plz
thanks !!

**Comment by atharvapatil123** [comment]
Hey  @Aman22sharma , I have added an algorithm for Tic-Tac-toe game. Please give it a check. It is for 1 player and 2nd player is AI.
PR number: #266
